# Generated by Django 5.0.3 on 2024-03-08 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.UUIDField(default=uuid.uuid4)),
                ('product_nane', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='enterprise_api.productmodel')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='raw_material', to='enterprise_api.rawmaterialmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WarehousesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouses', to='enterprise_api.rawmaterialmodel')),
            ],
        ),
    ]
