# Generated by Django 5.0.3 on 2024-03-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousesmodel',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-08'),
            preserve_default=False,
        ),
    ]
