# Generated by Django 5.0.3 on 2024-03-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_api', '0003_remove_productmodel_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterialmodel',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
