# Generated by Django 5.0.3 on 2024-03-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_api', '0004_alter_productmaterialmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_qty',
            new_name='product_code',
        ),
    ]
