# Generated by Django 5.0.3 on 2024-03-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_api', '0005_rename_product_qty_productmodel_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
