# Generated by Django 5.0.3 on 2024-03-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_api', '0006_remove_productmodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_products', to='enterprise_api.productmodel')),
            ],
        ),
    ]
