# Generated by Django 5.0.3 on 2024-03-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_api', '0007_factorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factorymodel',
            old_name='count',
            new_name='product_count',
        ),
    ]
