# Generated by Django 5.0.3 on 2024-03-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_api', '0008_rename_count_factorymodel_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_nane',
            new_name='product_name',
        ),
    ]
